# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_type_to_string
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - dangling_library_doc_comments
    - implicit_reprovide_this
    - invalid_case_patterns
    - library_annotations
    - matching_super_parameters
    - no_literal_bool_comparisons
    - no_self_assignments
    - no_wildcard_variable_uses
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - always_declare_return_types
    - unawaited_futures
    - avoid_void_async
    - cancel_subscriptions
    - directives_ordering
    - sized_box_for_whitespace
    - use_build_context_synchronously
    - sort_constructors_first
    - sort_pub_dependencies: false
    - prefer_single_quotes
    - require_trailing_commas
    - unnecessary_parenthesis

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
