// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpDHUaz7qJ-vlSmhMLPSw5mtL-inj3Yms',
    appId: '1:592587645836:web:f483b56ffbc438443eaca9',
    messagingSenderId: '592587645836',
    projectId: 'dexdo-21bc9',
    authDomain: 'dexdo-21bc9.firebaseapp.com',
    storageBucket: 'dexdo-21bc9.firebasestorage.app',
    measurementId: 'G-HCGR7ERNEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKQp9oZyCcpL0QczMPjGeU3iD-Z4lLmYE',
    appId: '1:592587645836:android:e4fb16e314689cf63eaca9',
    messagingSenderId: '592587645836',
    projectId: 'dexdo-21bc9',
    storageBucket: 'dexdo-21bc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBInpgRwPl2DjyJQqDcBM9GkOvUc2gp9c',
    appId: '1:592587645836:ios:d06b041d0961b7a93eaca9',
    messagingSenderId: '592587645836',
    projectId: 'dexdo-21bc9',
    storageBucket: 'dexdo-21bc9.firebasestorage.app',
    iosBundleId: 'com.dexify.dexdo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpDHUaz7qJ-vlSmhMLPSw5mtL-inj3Yms',
    appId: '1:592587645836:web:e290896682dc5f403eaca9',
    messagingSenderId: '592587645836',
    projectId: 'dexdo-21bc9',
    authDomain: 'dexdo-21bc9.firebaseapp.com',
    storageBucket: 'dexdo-21bc9.firebasestorage.app',
    measurementId: 'G-6GJRPQJ9B7',
  );
}
