import 'dart:async';
import 'dart:math' as math;
import 'dart:ui';
import 'package:dexdo/core/services/audio_service.dart';
import 'package:dexdo/core/services/speech_service.dart';
import 'package:dexdo/core/services/toast_service.dart';
import 'package:dexdo/core/utils/haptics.dart';
import 'package:dexdo/features/tasks/presentation/providers/task_provider.dart';
import 'package:dexdo/features/tasks/presentation/widgets/quick_task_sheet.dart';
import 'package:dexdo/shared/widgets/voice_preview_window.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

enum SmartFabPhase { idle, listening }

class SmartFab extends ConsumerStatefulWidget {
  const SmartFab({super.key});

  @override
  ConsumerState<SmartFab> createState() => _SmartFabState();
}

class _SmartFabState extends ConsumerState<SmartFab> with TickerProviderStateMixin {
  SmartFabPhase _phase = SmartFabPhase.idle;
  bool _isProcessingAI = false;

  // Animation Controllers
  late AnimationController _scaleController;
  late AnimationController _morphController;

  @override
  void initState() {
    super.initState();

    _scaleController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 250),
    );

    _morphController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 300),
    );
  }

  @override
  void dispose() {
    _scaleController.dispose();
    _morphController.dispose();
    super.dispose();
  }

  void _onLongPressStart(LongPressStartDetails details) {
    if (_phase != SmartFabPhase.idle) return;
    _startVoiceListening();
  }

  Future<void> _onLongPressEnd(LongPressEndDetails details) async {
    if (_phase == SmartFabPhase.listening) {
      // Release voice mode
      setState(() {
        _isProcessingAI = true;
      });

      // Stop listening and capture transcript
      final speechState = ref.read(speechProvider);
      final finalTranscript = speechState.lastWords.trim();

      await ref.read(speechProvider.notifier).stopListening();

      if (finalTranscript.isNotEmpty) {
        unawaited(AppHaptics.success());
        
        // Parse with Gemini NLP
        final parsed = await ref.read(taskProvider.notifier)
            .parseVoiceCommand(finalTranscript);

        // Create the task with parsed attributes
        await ref.read(taskProvider.notifier).addTask(
          title: parsed.title,
          dueDate: parsed.dueDate,
          priority: parsed.priority,
          category: parsed.category,
        );

        final createdTask = ref.read(taskProvider).tasks.first;

        // Populate subtasks if generated by AI
        if (parsed.subtasks != null && parsed.subtasks!.isNotEmpty) {
          for (var sub in parsed.subtasks!) {
            await ref.read(taskProvider.notifier).addSubtask(createdTask, sub);
          }
        }

        unawaited(AppHaptics.taskCreatedFromVoice());
        ref.read(toastProvider.notifier).showSuccess(
          'Task created: "${parsed.title}"',
          title: 'Voice Task Created',
          actionLabel: 'Undo',
          onAction: () {
            ref.read(taskProvider.notifier).deleteTask(createdTask);
          },
        );
      } else {
        ref.read(toastProvider.notifier).showWarning(
          'No speech recognized. Please try again.',
        );
      }

      setState(() {
        _isProcessingAI = false;
      });
      _resetFab();
    }
  }

  Future<void> _startVoiceListening() async {
    setState(() {
      _phase = SmartFabPhase.listening;
    });

    unawaited(AppHaptics.voiceModeEnter());
    unawaited(AudioService.playVoiceTriggerSound());
    unawaited(_morphController.forward());
    unawaited(_scaleController.animateTo(1.0, curve: Curves.elasticOut)); // Grow the mic FAB slightly
    
    // Start voice recording
    await ref.read(speechProvider.notifier).startListening();
  }

  void _resetFab() {
    unawaited(ref.read(speechProvider.notifier).cancelListening());
    
    unawaited(_scaleController.animateTo(0.0, curve: Curves.easeOut).then((_) {
      _scaleController.value = 0.0;
    }));
    unawaited(_morphController.reverse());

    setState(() {
      _phase = SmartFabPhase.idle;
    });
  }

  @override
  Widget build(BuildContext context) {
    final speechState = ref.watch(speechProvider);
    final taskState = ref.watch(taskProvider);

    // FAB Button size mapping
    const double fabSize = 56.0;

    return Stack(
      alignment: Alignment.center,
      clipBehavior: Clip.none,
      children: [
        // FLOATING VOICE PREVIEW WINDOW
        if (_phase == SmartFabPhase.listening)
          Positioned(
            bottom: 100,
            right: 0,
            child: IgnorePointer(
              ignoring: _isProcessingAI,
              child: VoicePreviewWindow(
                transcript: speechState.lastWords,
                categories: taskState.categories,
                isProcessing: _isProcessingAI,
              ),
            ),
          ),

        // MASTER FAB GESTURE WRAPPER
        GestureDetector(
          onLongPressStart: _onLongPressStart,
          onLongPressEnd: _onLongPressEnd,
          onTap: () {
            // Tap behaviour (Default QuickTaskSheet bottom sheet)
            FocusScope.of(context).unfocus();
            HapticFeedback.mediumImpact();
            showModalBottomSheet(
              context: context,
              isScrollControlled: true,
              backgroundColor: Colors.transparent,
              builder: (context) => const QuickTaskSheet(),
            );
          },
          child: ListenableBuilder(
            listenable: ListNotifier([_scaleController, _morphController]),
            builder: (context, child) {
              final double scale = 1.0 + (_scaleController.value * 0.2); // grows slightly when listening
              final double morph = _morphController.value;

              final isDark = Theme.of(context).brightness == Brightness.dark;
              return Transform.scale(
                scale: scale,
                child: Container(
                  width: fabSize,
                  height: fabSize,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withValues(alpha: 0.15),
                        blurRadius: 8,
                        offset: const Offset(0, 4),
                      ),
                    ],
                  ),
                  child: ClipOval(
                    child: BackdropFilter(
                      filter: ImageFilter.blur(sigmaX: 15, sigmaY: 15),
                      child: Container(
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: (isDark ? Colors.black : Colors.white).withValues(alpha: 0.25),
                          border: Border.all(
                            color: (isDark ? Colors.white : Colors.black).withValues(alpha: 0.15),
                            width: 1.0,
                          ),
                        ),
                        child: Center(
                          child: morph > 0.5
                              ? Icon(
                                  Icons.mic_none_rounded, // professional vertical mic icon
                                  color: isDark ? Colors.white : Colors.black87,
                                  size: 28,
                                )
                              : Transform.rotate(
                                  angle: morph * math.pi / 4, // rotate add icon slightly, leaving mic unrotated
                                  child: Icon(
                                    Icons.add_rounded,
                                    color: isDark ? Colors.white : Colors.black87,
                                    size: 32,
                                  ),
                                ),
                        ),
                      ),
                    ),
                  ),
                ),
              );
            },
          ),
        ),
      ],
    );
  }
}

// Utility class to listen to multiple animation controllers
class ListNotifier extends ChangeNotifier {
  ListNotifier(this.listenables) {
    for (final listenable in listenables) {
      listenable.addListener(notifyListeners);
    }
  }

  final List<Listenable> listenables;

  @override
  void dispose() {
    for (final listenable in listenables) {
      listenable.removeListener(notifyListeners);
    }
    super.dispose();
  }
}
